import type { Task, TaskDetails } from './Types';
export const departmentwiseslatasks: Task[] = [
  {
    id: 1,
    name: 'Development and Concepts',
    totalsteps: 3,
    completed: 2,
    inprogress: 1,
    slabreached: 0,
    new: 0,
  },
  {
    id: 2,
    name: 'Budgeting',
    totalsteps: 3,
    completed: 1,
    inprogress: 1,
    slabreached: 0,
    new: 1,
  },
  {
    id: 3,
    name: 'Technical Design',
    totalsteps: 3,
    completed: 2,
    inprogress: 0,
    slabreached: 0,
    new: 1,
  },
  {
    id: 4,
    name: 'Salesforce IT',
    totalsteps: 3,
    completed: 2,
    inprogress: 0,
    slabreached: 0,
    new: 1,
  },
  {
    id: 5,
    name: 'Central Planning',
    // startDate: '2026-05-10',
    // endDate: '2026-06-15',
    // status: 'new',
    // updatedBy: 'Sireesha Pulle',
    // lastUpdated: 'SLT-1148',
    totalsteps: 3,
    completed: 2,
    inprogress: 1,
    slabreached: 0,
    new: 0,
  },
];

export const departmentwiseTaskdetails: TaskDetails[] = [
  {
    taskName: 'Initiate Sales Tracker and Attach F&A Document',
    taskId: 'SLT-1148',
    startDate: '2026-06-05',
    endDate: '2026-06-05',
    updatedBy: 'Srujan',
  },
  {
    taskName: 'Capture Marketing Name and Launch Date',
    taskId: 'SLT-1148',
    startDate: '2026-06-05',
    endDate: '2026-06-05',
    updatedBy: 'Kautuk',
  },
  {
    taskName: 'DC HOD Approve or Reject',
    taskId: 'SLT-1148',
    startDate: '2026-06-05',
    endDate: '2026-06-05',
    updatedBy: 'Harish',
  },
];

export const overalldepartmentwiseslatasks: Task[] = [
  {
    id: 1,
    name: 'Development and Concepts',
    // startDate: '2026-06-05',
    // endDate: '2026-06-05',
    // status: 'completed',
    // updatedBy: 'Kautuk Shet',
    // caseId: 'SLT-1148',
    totalsteps: 6,
    completed: 4,
    inprogress: 2,
    slabreached: 0,
    new: 0,
  },
  {
    id: 2,
    name: 'Budgeting',
    // startDate: '2026-06-05',
    // endDate: '2026-06-05',
    // status: 'inprogress',
    // updatedBy: 'Muthyala Srujan',
    // caseId: 'SLT-1148',
    totalsteps: 6,
    completed: 2,
    inprogress: 2,
    slabreached: 0,
    new: 2,
  },
  {
    id: 3,
    name: 'Technical Design',
    // startDate: '2026-06-05',
    // endDate: '2026-06-05',
    // status: 'inprogress',
    // updatedBy: 'Rajesh',
    // caseId: 'SLT-1148',
    totalsteps: 6,
    completed: 4,
    inprogress: 0,
    slabreached: 0,
    new: 2,
  },
  {
    id: 4,
    name: 'Salesforce IT',
    // startDate: '2026-05-06',
    // endDate: '2026-08-15',
    // status: 'inprogress',
    // updatedBy: 'Raviteja Dhanukonda',
    // lastUpdated: 'SLT-1148',
    totalsteps: 6,
    completed: 4,
    inprogress: 0,
    slabreached: 0,
    new: 2,
  },
  {
    id: 5,
    name: 'Central Planning',
    // startDate: '2026-05-10',
    // endDate: '2026-06-15',
    // status: 'new',
    // updatedBy: 'Sireesha Pulle',
    // lastUpdated: 'SLT-1148',
    totalsteps: 6,
    completed: 4,
    inprogress: 2,
    slabreached: 0,
    new: 0,
  },
];

export const overalldepartmentwiseTaskdetails: TaskDetails[] = [
  {
    taskName: 'Initiate Sales Tracker and Attach F&A Document',
    taskId: 'SLT-1149',
    startDate: '2026-06-06',
    endDate: '2026-06-06',
    updatedBy: 'Srujan',
  },
  {
    taskName: 'Capture Marketing Name and Launch Date',
    taskId: 'SLT-1149',
    startDate: '2026-06-06',
    endDate: '2026-06-06',
    updatedBy: 'Kautuk',
  },
  {
    taskName: 'DC HOD Approve or Reject',
    taskId: 'SLT-1149',
    startDate: '2026-06-06',
    endDate: '2026-06-06',
    updatedBy: 'Harish',
  },
  ...departmentwiseTaskdetails,
];