import type { Task } from './Types';

export const tasksProgress: Task[] = [
  {
    id: 1,
    name: 'Tracker Initiation & Upload Documents by Design & Concept',
    startDate: '2026-05-07',
    endDate: '2026-08-17',
    progress: 100,
    status: 'completed',
    updatedBy: 'Kautuk Shet',
    lastUpdated: '2026-05-05',

    completed: 10,
    inprogress: 0,
    slabreached: 0,
    delayed: 0,
    pending: 0,
    new: 0,
    autocomplete: 5,
  },
  {
    id: 2,
    name: 'D&C HOD Approve F&A',
    startDate: '2026-06-03',
    endDate: '2026-09-10',
    progress: 60,
    status: 'inprogress',
    updatedBy: 'Muthyala Srujan',
    lastUpdated: '2026-05-07',

    completed: 2,
    inprogress: 8,
    slabreached: 2,
    delayed: 0,
    pending: 1,
    new: 0,
    autocomplete: 0,
  },
  {
    id: 3,
    name: 'Budgeting HOD Approve F&A',
    startDate: '2026-05-10',
    endDate: '2026-08-12',
    progress: 20,
    status: 'delay',
    updatedBy: 'Rajesh',
    lastUpdated: '2026-08-12',

    completed: 1,
    inprogress: 2,
    slabreached: 6,
    delayed: 3,
    pending: 3,
    new: 1,
    autocomplete: 0,
  },
  {
    id: 4,
    name: 'Technical Design HOD Approve F&A',
    startDate: '2026-05-06',
    endDate: '2026-08-15',
    progress: 40,
    status: 'inprogress',
    updatedBy: 'Raviteja Dhanukonda',
    lastUpdated: '2026-05-09',

    completed: 2,
    inprogress: 5,
    delayed: 0,
    slabreached: 1,
    pending: 2,
    new: 0,
    autocomplete: 0,
  },
  {
    id: 5,
    name: 'Property ID and Location ID Creation',
    startDate: '2026-05-10',
    endDate: '',
    progress: 0,
    status: 'notstarted',
    updatedBy: '',
    lastUpdated: '2026-05-10',

    completed: 0,
    inprogress: 0,
    slabreached: 0,
    delayed: 2,
    pending: 10,
    new: 12,
    autocomplete: 0,
  },
];